//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EyeTracking.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EYETRACKING_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_SACCADE_DLG                 129
#define IDD_PURSUIT_DLG                 130
#define IDD_CALIBRATION_DLG             131
#define IDD_SETTINGS_DLG                132
#define IDI_ICON1                       133
#define IDD_FULLFIELD_DLG               134
#define IDD_STEPRAMP_DLG                135
#define IDD_SCENE_CALIBRATION           138
#define IDD_OCULAR_FOLLOWING            139
#define IDD_ISOLUMINANT_PATCH           140
#define IDD_NOISE_GRATING_DLG           141
#define IDD_PREF_SEL_DLG                142
#define IDD_ORIENTATION_TUNING_DLG      144
#define IDD_RF_MAPPING_DLG              145
#define IDD_CIRCLE_ANNULUS_DLG          146
#define IDD_APD_DLG                     147
#define IDD_REMEMBER_DLG                148
#define IDD_SUPPRESSION_DLG             149
#define IDD_ALTERNATION_DLG             150
#define IDD_MSEQUENCE_DLG               151
#define IDR_ACCELERATOR1                152
#define IDR_MENU1                       156
#define ID_RESPONSE_RED                 157
#define ID_RESPONSE_BLUE                158
#define ID_RESPONSE_BOTH                159
#define ID_RESPONSE_NOTHING             160
#define IDD_RULER_DLG                   162
#define IDD_AMBLYOSCOPE_DLG             163
#define IDD_SCOTOMA_MAP_DLG             164
#define IDD_ANAGLYPH_DLG                165
#define IDD_GRATINGS_DLG                166
#define IDD_SACCADE_TRIALS_DLG          167
#define IDD_TRIAL_SACCADES_DLG          167
#define IDD_FIXATIONSTAB_DLG            168
#define IDD_REVERSEFIX_DLG              170
#define IDD_SPARSE_NOISE_DLG            172
#define ID_RUN                          1000
#define ID_EXIT                         1001
#define IDC_TAB1                        1002
#define IDC_TABS                        1002
#define IDC_NUp                         1002
#define IDC_RadioVertical               1003
#define IDC_MinContrast                 1003
#define IDC_CheckReturnToPt             1004
#define IDC_NDown                       1004
#define IDC_CheckUseAllDir              1005
#define IDC_RadioHorizontal             1006
#define IDC_MaxContrast                 1006
#define IDC_Radio45Deg                  1007
#define IDC_CoarseStep                  1007
#define IDC_Radio135Deg                 1008
#define IDC_FineStep                    1008
#define IDC_RadioRadial                 1009
#define IDC_CurrFreq                    1009
#define IDC_RadioXY                     1010
#define IDC_CurrContrast                1010
#define IDC_ButtonApply                 1011
#define IDC_EditDotSize                 1012
#define IDC_ButtonStartMotion           1012
#define IDC_NumReversals                1012
#define IDC_EditStepSize                1013
#define IDC_EditAmplitude               1013
#define IDC_GratingHeight               1013
#define IDC_EditFrequency               1014
#define IDC_GratingWidth                1014
#define IDC_EditNumSteps                1015
#define IDC_EditSize                    1015
#define IDC_DotPosition                 1015
#define IDC_EditDuration                1016
#define IDC_EditDistance                1016
#define IDC_MeanLevel                   1016
#define IDC_GratingPosition             1016
#define IDC_EditPointY                  1017
#define IDC_RadioTriangle               1017
#define IDC_NoiseAmplitude              1017
#define IDC_CurrPosition                1017
#define IDC_EditPointX                  1018
#define IDC_RadioSinewave               1018
#define IDC_MaskRadius                  1018
#define IDC_FreqMin                     1019
#define IDC_BlankTime                   1019
#define IDC_OrientationMin              1020
#define IDC_EditSeparation              1021
#define IDC_WidthMin                    1021
#define IDC_HSeparation                 1021
#define IDC_HeightMin                   1022
#define IDC_EditSeparation2             1022
#define IDC_VSeparation                 1022
#define IDC_BUTTON1                     1023
#define IDC_XPos                        1023
#define IDC_CheckHorizontal             1024
#define IDC_YPos                        1024
#define IDC_SaveSettings                1024
#define IDC_SecondaryAdd                1024
#define IDC_BUTTON3                     1024
#define IDC_CheckVertical               1025
#define IDC_FreqMax                     1025
#define IDC_BUTTON4                     1025
#define IDC_Check45Deg                  1026
#define IDC_NoiseType                   1026
#define IDC_BUTTON5                     1026
#define IDC_Check135Deg                 1027
#define IDC_MaskBlending                1027
#define IDC_EditRed                     1028
#define IDC_FreqStep                    1028
#define IDC_EditGreen                   1029
#define IDC_UseMask                     1029
#define IDC_MakeDefault                 1029
#define IDC_EditBlue                    1030
#define IDC_ContrastMin                 1030
#define IDC_MEDIUM_STEP                 1030
#define IDC_EditRedBG                   1031
#define IDC_ContrastMax                 1031
#define IDC_InitialContrasts            1031
#define IDC_EditGreenBG                 1032
#define IDC_Radio_GratingSinewave       1032
#define IDC_LoadDefault                 1032
#define IDC_EditBlueBG                  1033
#define IDC_Radio_GratingSquareWave     1033
#define IDC_EditXOffset                 1034
#define IDC_ContrastStep                1034
#define IDC_EditYOffset                 1035
#define IDC_FreqSetPt                   1035
#define IDC_APPLY                       1036
#define IDC_ContrastSetPt               1037
#define IDC_OrientationMax              1041
#define IDC_OrientationStep             1042
#define IDC_OrientationSetPt            1044
#define IDC_WidthMax                    1045
#define IDC_WidthStep                   1046
#define IDC_Check_AutoWidth             1047
#define IDC_WidthSetPt                  1048
#define IDC_EditVelocity                1049
#define IDC_HeightMax                   1049
#define IDC_EditFixationSize            1050
#define IDC_HeightStep                  1050
#define IDC_EditFixationRed             1051
#define IDC_Check_AutoHeight            1051
#define IDC_EditFixationGreen           1052
#define IDC_HeightSetPt                 1052
#define IDC_EditFixationBlue            1053
#define IDC_PhaseMin                    1053
#define IDC_RadioUp                     1054
#define IDC_PhaseMax                    1054
#define IDC_RadioDown                   1055
#define IDC_PhaseStep                   1055
#define IDC_RadioLeft                   1056
#define IDC_Check_AutoPhase             1056
#define IDC_RadioRight                  1057
#define IDC_PhaseSetPt                  1057
#define IDC_EditWidth                   1058
#define IDC_AutomationSpeed             1058
#define IDC_CheckFixation               1059
#define IDC_UseMouseControl             1059
#define IDC_Check_AutoFreq              1060
#define IDC_Check_AutoContrast          1061
#define IDC_Check_AutoOrientation       1062
#define IDC_EditExcursion               1063
#define IDC_EditDelay                   1064
#define IDC_EditFixtionXPos             1065
#define IDC_EditPlateau                 1065
#define IDC_ReversalsCompleted          1065
#define IDC_EditFixationYPos            1066
#define IDC_IncreaseStep                1066
#define IDC_DecreaseStep                1067
#define IDC_EditOffDelay                1068
#define IDC_CurrStepSize                1068
#define IDC_ButtonAll                   1069
#define IDC_UBERFINESTEP                1069
#define IDC_ButtonNone                  1070
#define IDC_CheckUp                     1071
#define IDC_CheckDown                   1072
#define IDC_CheckLeft                   1073
#define IDC_CheckRight                  1074
#define IDC_DURATION                    1075
#define IDC_EditContrast                1076
#define IDC_EditDegPerVolt              1077
#define IDC_EditScreenXOffset           1078
#define IDC_EditScreenYOffset           1079
#define IDC_EditFreq                    1080
#define IDC_EditDegPerVolt2             1080
#define IDC_PixelSize                   1080
#define IDC_EditCorrectTimeOut          1081
#define IDC_EditTimeOut                 1084
#define IDC_MIN_DURATION                1094
#define IDC_MAX_DURATION                1095
#define IDC_RANDOM_DURATIONS            1096
#define IDC_HighFreqAmplitude           1097
#define IDC_HighFreq                    1098
#define IDC_EnableHighFreq              1099
#define IDC_OscillationAmplitude        1100
#define IDC_OscillationFreq             1101
#define IDC_EnableOscillations          1102
#define IDC_Check_ShowAll               1103
#define IDC_ImagePath                   1104
#define IDC_XPosition                   1105
#define IDC_YPosition                   1106
#define IDC_Check_Behvaior              1107
#define IDC_Check_Behavior              1108
#define IDC_AVOID_EYE                   1109
#define IDC_FX_X_POS                    1110
#define IDC_FX_Y_POS                    1111
#define IDC_FX_SIZE                     1112
#define IDC_BKG_SPEED                   1117
#define IDC_POST_SACCADE_LAT            1118
#define IDC_BKG_STEP_DURATION           1119
#define IDC_TIMEOUT                     1120
#define IDC_EditEyePosition             1121
#define IDC_EditScreenPosition          1122
#define IDC_FileName                    1124
#define IDC_Browse                      1130
#define IDC_VoltageRange                1132
#define IDC_VoltageOffset               1133
#define IDC_DotSize                     1139
#define IDC_Edit_TargetDelay            1141
#define IDC_HIGHEST_PRIORITY            1142
#define IDC_BarWidth                    1143
#define IDC_BarHeight                   1144
#define IDC_AngularStep                 1145
#define IDC_rfmStepsX                   1145
#define IDC_MotionStep                  1146
#define IDC_rfmStepSizeDeg              1146
#define IDC_IntertrialTime              1147
#define IDC_TrialDuration               1148
#define IDC_nRepeats                    1149
#define IDC_UnitTag                     1152
#define IDC_STATIC_ORIENTATION          1153
#define IDC_STATIC_REPEAT               1154
#define IDC_STATIC_TRIALS_LEFT          1155
#define IDC_START_PRESENTATION          1156
#define IDC_FixationSize                1183
#define IDC_STIM_DATA                   1184
#define IDC_FixationX                   1185
#define IDC_FixationY                   1186
#define IDC_MEAN_LUMINANCE              1187
#define IDC_RADIO_FNOISE                1188
#define IDC_RADIO_NON_FNOISE            1189
#define IDC_NUM_REPEATS                 1190
#define IDC_FixationX2                  1191
#define IDC_FixationY2                  1192
#define IDC_EYE_LIST                    1193
#define IDC_STATIC_DEBUG                1194
#define IDC_AcceptDelay                 1195
#define IDC_LoadSettings                1198
#define IDC_MaxDisplayDuration          1199
#define IDC_RepeatsOnly                 1200
#define IDC_MinLuminance                1201
#define IDC_MaxLuminance                1202
#define IDC_AnnulusWidthMin             1208
#define IDC_AnnulusWidthMax             1209
#define IDC_AnnulusWidthStep            1210
#define IDC_BlankPeriod                 1218
#define IDC_CirclesOnly                 1231
#define IDC_AnnuliOnly                  1232
#define IDC_Height                      1238
#define IDC_Circle                      1239
#define IDC_Bar                         1240
#define IDC_MouseControl                1241
#define IDC_rfmUseMouse                 1241
#define IDC_Pulse                       1242
#define IDC_SaveAsLeft                  1243
#define IDC_SaveAsRight                 1244
#define IDC_StaticLeftEye               1245
#define IDC_StaticRightEye              1246
#define ID_APPLY                        1247
#define IDC_rfmBlanks                   1247
#define IDC_RightEyeField               1248
#define IDC_rfmUseGrid                  1248
#define IDC_LeftEyeField                1249
#define IDC_InterleavedFields           1250
#define IDC_ManualFields                1251
#define IDC_IntertrialDuration          1255
#define IDC_CirclesAnnuli               1258
#define IDC_CheckOnOff                  1259
#define IDC_RadiusMin                   1260
#define IDC_RadiusMax                   1261
#define IDC_RadiusStep                  1262
#define IDC_PrimaryRed                  1266
#define IDC_PrimaryGreen                1267
#define IDC_PrimaryBlue                 1268
#define IDC_PrimaryRemove               1269
#define IDC_PrimaryClear                1270
#define IDC_PrimaryList                 1271
#define IDC_Width                       1272
#define IDC_SecondaryRed                1272
#define IDC_SecondaryGreen              1273
#define IDC_SecondaryBlue               1274
#define IDC_HCenter                     1274
#define IDC_Orientation                 1275
#define IDC_SecondaryRemove             1275
#define IDC_VCenter                     1275
#define IDC_CircleRadius                1276
#define IDC_SecondaryClear              1276
#define IDC_SecondaryList               1277
#define IDC_rfmStepsY                   1277
#define IDC_PrimaryAdd                  1278
#define IDC_rfmDisplayTimeMs            1278
#define IDC_Repeats                     1279
#define IDC_rfmBlankTimeMs              1279
#define IDC_StaticRadius                1280
#define IDC_StaticAnnulusWidth          1281
#define IDC_StartAngle                  1281
#define IDC_StaticRepeat                1282
#define IDC_EDIT2                       1282
#define IDC_EndAngle                    1282
#define IDC_FIXATION_POSY               1282
#define IDC_AlternateBlockSize          1282
#define IDC_GridSize                    1282
#define IDC_Tap                         1282
#define IDC_Diamond                     1282
#define IDC_Red                         1282
#define IDC_ChangeR                     1282
#define IDC_GaborSD                     1282
#define IDC_StaticTrialsLeft            1283
#define IDC_Tap2                        1283
#define IDC_Blue                        1283
#define IDC_xLoc                        1283
#define IDC_EDIT9                       1283
#define IDC_xLocL                       1283
#define IDC_FixLocL                     1283
#define IDC_CHECK_CYCLE                 1284
#define IDC_Tap3                        1284
#define IDC_BGDisparity                 1284
#define IDC_yLoc                        1284
#define IDC_yLocL                       1284
#define IDC_snDarkCount                 1284
#define IDC_snSecondaryCount            1284
#define IDC_JITTER                      1285
#define IDC_RedR                        1285
#define IDC_BGDisparity2                1285
#define IDC_snTertiaryCount             1285
#define IDC_AVOID_ZERO                  1286
#define IDC_RedG                        1286
#define IDC_JITTERY                     1287
#define IDC_RedB                        1287
#define IDC_snNumFrames                 1287
#define IDC_RadioPrimary                1288
#define IDC_GreenR                      1288
#define IDC_snMinDist                   1288
#define IDC_RadioSecondary              1289
#define IDC_GreenG                      1289
#define IDC_RadioAlternate              1290
#define IDC_GreenB                      1290
#define IDC_EditRedSec                  1291
#define IDC_BlueR                       1291
#define IDC_EditGreenSec                1292
#define IDC_BlueG                       1292
#define IDC_EditBlueSec                 1293
#define IDC_BlueB                       1293
#define IDC_RadioRandom                 1294
#define IDC_TRAINING                    1295
#define IDC_PCT_TRIALS_RIGHT            1296
#define IDC_SHOW_FIXATION               1297
#define IDC_FIXATION_POSX               1298
#define IDC_FIXATION_RED                1299
#define IDC_FIXATION_GREEN              1300
#define IDC_FIXATION_BLUE               1301
#define IDC_ON_RED                      1302
#define IDC_ON_GREEN                    1303
#define IDC_ON_BLUE                     1304
#define IDC_ON_TIME                     1305
#define IDC_OFF_TIME                    1306
#define IDC_OFF_RED                     1307
#define IDC_OFF_GREEN                   1308
#define IDC_OFF_BLUE                    1309
#define IDC_FIXATION_SIZE               1310
#define IDC_LEFT_FIELD                  1311
#define IDC_RIGHT_FIELD                 1312
#define IDC_ALTERNATE                   1313
#define IDC_FULLSCREEN                  1314
#define IDC_ALTERNATE_DELAY             1315
#define IDC_BEHAVIOR                    1316
#define IDC_FIXATION_DELAY              1317
#define IDC_FIELD_WIDTH                 1318
#define IDC_FIELD_HEIGHT                1319
#define IDC_CENTER_X_LEFT               1320
#define IDC_CENTER_Y_LEFT               1321
#define IDC_CENTER_X_RIGHT              1322
#define IDC_CENTER_Y_RIGHT              1323
#define IDC_CenterXPos                  1324
#define IDC_CenterYPos                  1325
#define IDC_FlashInterval               1326
#define IDC_FlashDuration               1327
#define IDC_CenterXPos2                 1327
#define IDC_smNumStepsX                 1327
#define IDC_StepSize                    1328
#define IDC_NumSteps                    1329
#define IDC_NumStepsH                   1329
#define IDC_CenterSecondaryRed          1330
#define IDC_CenterYPos2                 1330
#define IDC_smNumStepsY                 1330
#define IDC_smStepSizeDeg               1331
#define IDC_CenterSecondaryGreen        1331
#define IDC_CenterSecondaryBlue         1332
#define IDC_NumStepsV                   1333
#define IDC_CenterRadioPrimary          1334
#define IDC_CenterRadioAlternate        1335
#define IDC_StepHoriz                   1336
#define IDC_StepVert                    1337
#define IDC_Step45                      1338
#define IDC_Step135                     1339
#define IDC_PeriphDotSize               1340
#define IDC_CenterRadioSecondary        1341
#define IDC_CenterRadioRandomize        1342
#define IDC_CenterPrimaryRed            1343
#define IDC_CenterPrimaryGreen          1344
#define IDC_CenterPrimaryBlue           1345
#define IDC_PeriphSecondaryRed          1346
#define IDC_PeriphSecondaryGreen        1347
#define IDC_PeriphSecondaryBlue         1348
#define IDC_PeriphRadioPrimary          1349
#define IDC_PeriphRadioSecondary        1350
#define IDC_PeriphRadioAlternate        1351
#define IDC_PeriphRadioRandomize        1352
#define IDC_PeriphPrimaryRed            1353
#define IDC_PeriphPrimaryGreen          1354
#define IDC_PeriphPrimaryBlue           1355
#define IDC_DistRadial                  1356
#define IDC_DistXY                      1357
#define IDC_NoiseRed                    1358
#define IDC_MaxDelay                    1359
#define IDC_NoiseGreen                  1360
#define IDC_MEMORY_GUIDED               1361
#define IDC_PERIPHERAL_FLASH            1362
#define IDC_POST_FLASH_DELAY            1363
#define IDC_EDIT3                       1364
#define IDC_INTERTRIAL_DELAY            1364
#define IDC_SpatialFreq                 1364
#define IDC_TextDisparity               1364
#define IDC_NumAngles                   1364
#define IDC_NoiseBlue                   1365
#define IDC_NumPhases                   1365
#define IDC_EDIT4                       1365
#define IDC_AvoidZero                   1366
#define IDC_EDIT5                       1366
#define IDC_PeriphTertiaryRed           1367
#define IDC_EDIT6                       1367
#define IDC_RedBlue                     1368
#define IDC_EDIT7                       1368
#define IDC_GridSpace                   1369
#define IDC_PeriphTertiaryGreen         1369
#define IDC_StripeHeight                1370
#define IDC_PeriphTertiaryBlue          1370
#define IDC_Delay                       1371
#define IDC_PeriphRadioTertiary         1371
#define IDC_EditNumStepsY               1372
#define IDC_Blank                       1372
#define IDC_DotSize1                    1373
#define IDC_XPos1                       1374
#define IDC_YPos1                       1375
#define IDC_RandomizePostFlash          1375
#define IDC_Red1                        1376
#define IDC_RandomizeFlashInterval      1376
#define IDC_Green1                      1377
#define IDC_PostFlashRandMin            1377
#define IDC_Blue1                       1378
#define IDC_PostFlashRandMax            1378
#define IDC_DotSize2                    1379
#define IDC_FlashIntervalRandMin        1379
#define IDC_XPos2                       1380
#define IDC_FlashIntervalRandMax        1380
#define IDC_YPos2                       1381
#define IDC_PrimaryStatic               1381
#define IDC_Red2                        1382
#define IDC_SecondaryStatic             1382
#define IDC_DotStatic                   1382
#define IDC_green2                      1383
#define IDC_Green2                      1383
#define IDC_BackgroundStatic            1383
#define IDC_Blue2                       1384
#define IDC_CenterPrimaryStatic         1384
#define IDC_CenterSecondaryStatic       1385
#define IDC_PeriphSecondaryStatic       1386
#define IDC_PeriphPrimaryStatic         1387
#define IDC_PeriphXPos                  1388
#define IDC_PeriphXPosR                 1388
#define IDC_PeriphYPos                  1389
#define IDC_PeriphYPosR                 1389
#define IDC_PeriphXRadius               1390
#define IDC_PeriphYRadius               1391
#define IDC_PctTimeAtPeriph             1392
#define IDC_NoiseStatic                 1393
#define IDC_PeriphTertiaryStatic        1394
#define IDC_CHECK_SEQ_RANDOM            1395
#define IDC_RedScroll                   1396
#define IDC_CenterXRadius               1396
#define IDC_BlueScroll                  1397
#define IDC_CenterYRadius               1397
#define IDC_RedStatic                   1398
#define IDC_EnrichedXRadius             1398
#define IDC_BlueStatic                  1399
#define IDC_EnrichedYRadius             1399
#define IDC_EnrichedX                   1400
#define IDC_FFTest                      1401
#define IDC_EnrichedY                   1401
#define IDC_MMTest                      1402
#define IDC_Delayms                     1404
#define IDC_RedBlock                    1405
#define IDC_bgStripeLightRed            1406
#define IDC_bgStripeLightGreen          1407
#define IDC_bgStripeLightBlue           1408
#define IDC_bgStripeDarkRed             1409
#define IDC_bgStripeDarkGreen           1410
#define IDC_bgStripeDarkBlue            1411
#define IDC_BlueBlock                   1412
#define IDC_TextValues                  1413
#define IDC_AdjustBG                    1414
#define IDC_UseString                   1415
#define IDC_TextString                  1416
#define IDC_Order                       1417
#define IDC_NumBars                     1418
#define IDC_Order2                      1419
#define IDC_Vertical                    1420
#define IDC_CurrentOffset               1421
#define IDC_NumRandomRepeats            1422
#define IDC_Order3                      1422
#define IDC_UseNoise                    1423
#define IDC_COUNTDOWN                   1424
#define IDC_NumCatchTrials              1425
#define IDC_COUNTDOWN2                  1426
#define IDC_GridSteps                   1427
#define IDC_NoiseSize                   1428
#define IDC_Textmarks                   1432
#define IDC_CrossPix                    1433
#define IDC_NumBlankTrials              1434
#define IDC_NoisePct                    1435
#define IDC_UseDim                      1436
#define IDC_NoisePct2                   1436
#define IDC_NoiseContrast               1436
#define IDC_DimOnsetMin                 1437
#define IDC_DimOnsetMax                 1439
#define IDC_DimTimeout                  1440
#define IDC_AnswerPeriod                1441
#define IDC_EDIT1                       1442
#define IDC_DimBrightness               1442
#define IDC_DotTime                     1442
#define IDC_MinRadius                   1442
#define IDC_NumRings                    1442
#define IDC_Text                        1442
#define IDC_Eccentricity                1442
#define IDC_StartXUp                    1442
#define IDC_GratingRed                  1442
#define IDC_FixY                        1442
#define IDC_PctMonocular                1442
#define IDC_StimX                       1442
#define IDC_ShutterInterleavedN         1442
#define IDC_NSamples                    1442
#define IDC_MisbehaviorDelay            1442
#define IDC_rfmCrossX                   1442
#define IDC_tbsPctPurpleCtr             1442
#define IDC_tbsCueTimeMin               1442
#define IDC_revInitLeftX                1442
#define IDC_snFolderName                1442
#define IDC_DisplayTime                 1443
#define IDC_MaxRadius                   1443
#define IDC_LGreen                      1443
#define IDC_Image                       1443
#define IDC_ChangeG                     1443
#define IDC_StartYUp                    1443
#define IDC_GratingGreen                1443
#define IDC_tbsCueTimeMax               1443
#define IDC_rfmCrossX2                  1443
#define IDC_revInitLeftY                1443
#define IDC_HideCenter                  1444
#define IDC_OffTime                     1444
#define IDC_LBlue                       1444
#define IDC_ChangeB                     1444
#define IDC_StartXDown                  1444
#define IDC_GratingBlue                 1444
#define IDC_FixD                        1444
#define IDC_tbsDelayTimeMin             1444
#define IDC_rfmSwapInt                  1444
#define IDC_revInitRightX               1444
#define IDC_InterleaveNoise             1445
#define IDC_RRed                        1445
#define IDC_StartYDown                  1445
#define IDC_GratingRed2                 1445
#define IDC_tbsDelayTimeMax             1445
#define IDC_rfmWindowAllowancePix       1445
#define IDC_revInitRightY               1445
#define IDC_RGreen                      1446
#define IDC_StartXLeft                  1446
#define IDC_GratingGreen2               1446
#define IDC_tbsLingerTimeMin            1446
#define IDC_revWindowAllowancePix       1446
#define IDC_CHECK3                      1447
#define IDC_RBlue                       1447
#define IDC_StartYLeft                  1447
#define IDC_GratingBlue2                1447
#define IDC_tbsLingerTimeMax            1447
#define IDC_CenterPoints                1448
#define IDC_StartXRight                 1448
#define IDC_Pause                       1449
#define IDC_StartYRight                 1449
#define IDC_BUTTON2                     1450
#define IDC_OffAxis                     1451
#define IDC_BUTTON6                     1452
#define IDC_Response                    1454
#define IDC_ResponseTimeout             1455
#define IDC_PeriphXPosL                 1457
#define IDC_PeriphYPosL                 1458
#define IDC_RampDuration                1460
#define IDC_RampUp                      1461
#define IDC_MMSineGratings              1462
#define IDC_RBUpDown                    1463
#define IDC_RBRandom                    1464
#define IDC_RBSlider                    1465
#define IDC_MMMG                        1467
#define IDC_NumGratings                 1469
#define IDC_LeftEyeStatic               1470
#define IDC_RightEyeStatic              1471
#define IDC_MultipleFullBlue            1472
#define IDC_Dot1                        1474
#define IDC_Dot2                        1475
#define IDC_CatchPctR                   1475
#define IDC_Dot3                        1476
#define IDC_CatchPctB                   1476
#define IDC_Dot4                        1477
#define IDC_CatchPctN                   1477
#define IDC_Dot5                        1478
#define IDC_Dot6                        1479
#define IDC_PctTimeAtCenter             1479
#define IDC_Dot7                        1480
#define IDC_NumCatchTrials2             1480
#define IDC_Dot8                        1481
#define IDC_Box                         1481
#define IDC_PctTimeAtEnriched           1481
#define IDC_Dot9                        1482
#define IDC_RADIO1                      1482
#define IDC_ViewPurple                  1482
#define IDC_PointDot                    1482
#define IDC_Horiz                       1482
#define IDC_RadioText                   1482
#define IDC_TypeSquare                  1482
#define IDC_RADIO2                      1483
#define IDC_ViewRed                     1483
#define IDC_PointLandoltC               1483
#define IDC_Vert                        1483
#define IDC_RadioImage                  1483
#define IDC_TypeSine                    1483
#define IDC_RADIO3                      1484
#define IDC_XOffset                     1484
#define IDC_ViewBlue                    1484
#define IDC_PointE                      1484
#define IDC_RadioShapes                 1484
#define IDC_TypeGabor                   1484
#define IDC_tbsSaccadeTriggerRadioFlash 1484
#define IDC_RadioCir                    1484
#define IDC_YOffset                     1485
#define IDC_PhaseRandom                 1485
#define IDC_LRed                        1486
#define IDC_PhaseStatic                 1486
#define IDC_Clock                       1487
#define IDC_PhaseRotate                 1487
#define IDC_Bird                        1488
#define IDC_AngleRandom                 1488
#define IDC_Cross                       1489
#define IDC_AngleStatic                 1489
#define IDC_XOffsetDeg                  1490
#define IDC_AngleRotate                 1490
#define IDC_YOffsetDeg                  1491
#define IDC_LeftRight                   1492
#define IDC_Llabel                      1493
#define IDC_Rlabel                      1494
#define IDC_Background                  1495
#define IDC_RADIO4                      1496
#define IDC_AutoLB                      1497
#define IDC_RewardAny                   1497
#define IDC_Noise                       1498
#define IDC_RADIO7                      1498
#define IDC_RewardTertiary              1498
#define IDC_TertiaryStatic              1499
#define IDC_TertiaryRed                 1500
#define IDC_AutoRB                      1500
#define IDC_TertiaryGreen               1501
#define IDC_RADIO8                      1501
#define IDC_AutoLRB                     1501
#define IDC_TertiaryBlue                1502
#define IDC_ResponseDelay               1503
#define IDC_WrongDelay                  1504
#define IDC_RandomizeDisplayTime        1505
#define IDC_DisplayRandMin              1506
#define IDC_DisplayRandMax              1507
#define IDC_CenterDotSize               1508
#define IDC_MaxDisparity                1510
#define IDC_CHECK1                      1511
#define IDC_SPIN1                       1512
#define IDC_rfmCheckPrimaryR            1512
#define IDC_SPIN2                       1513
#define IDC_SequentialOrder             1513
#define IDC_rfmCheckSecondaryL          1513
#define IDC_SPIN3                       1514
#define IDC_BUTTON_BROWSE               1514
#define IDC_rfmCheckSecondaryR          1514
#define IDC_SPIN4                       1515
#define IDC_StaticPhase                 1515
#define IDC_rfmCheckTertiaryL           1515
#define IDC_rfmCheckTertiaryR           1516
#define IDC_StaticAngle                 1517
#define IDC_NumAnglesStatic             1518
#define IDC_NumAnglesStatic2            1519
#define IDC_NumRepeats                  1521
#define IDC_LeftEye                     1522
#define IDC_RightEye                    1523
#define IDC_Interleaved                 1524
#define IDC_Interleaved2                1525
#define IDC_Both                        1525
#define IDC_LeftStatic                  1526
#define IDC_RightStatic                 1527
#define IDC_PresentationCounter         1528
#define IDC_Initiation                  1529
#define IDC_Reward                      1530
#define IDC_FixX                        1530
#define IDC_EDIT8                       1532
#define IDC_GratingsPerSaccade          1532
#define IDC_DeviatedRightX              1533
#define IDC_DeviatedRightY              1534
#define IDC_DeviatedLeftX               1535
#define IDC_DeviatedLeftY               1536
#define IDC_RADIO5                      1537
#define IDC_FlashBlocks                 1538
#define IDC_RFMapR                      1538
#define IDC_ArmLength                   1539
#define IDC_ArmWidth                    1540
#define IDC_SpaceSize                   1541
#define IDC_ArmStatic                   1542
#define IDC_FixationDot                 1543
#define IDC_CenterX                     1544
#define IDC_CenterY                     1545
#define IDC_BGBrightness                1546
#define IDC_CHECK2                      1547
#define IDC_DotColor                    1549
#define IDC_DotPic                      1550
#define IDC_DotText                     1551
#define IDC_BackgroundColor             1552
#define IDC_BackgroundText              1553
#define IDC_BackgroundPic               1554
#define IDC_StimXStatic                 1555
#define IDC_StimYStatic                 1556
#define IDC_StimY                       1557
#define IDC_StimXSpin                   1558
#define IDC_StimYSpin                   1559
#define IDC_ApplySettings               1560
#define IDC_ScreenYStatic               1561
#define IDC_ScreenXStatic               1562
#define IDC_ScreenX                     1563
#define IDC_ScreenY                     1564
#define IDC_ScreenXSpin                 1565
#define IDC_ScreenYSpin                 1566
#define IDC_LightPic                    1567
#define IDC_LightText                   1568
#define IDC_DarkText                    1570
#define IDC_DarkPic                     1571
#define IDC_ShutterL                    1572
#define IDC_ShutterR                    1573
#define IDC_ShutterLState               1574
#define IDC_ShutterRState               1575
#define IDC_ShutterRandom               1575
#define IDC_ShutterManual               1576
#define IDC_ShutterInterleaved          1577
#define IDC_AutoLR                      1578
#define IDC_EyePositions                1580
#define IDC_Fovea                       1581
#define IDC_AutoPosition                1582
#define IDC_RewardCorrect               1584
#define IDC_TertiaryRewardPct           1585
#define IDC_ShutterDelay                1586
#define IDC_RewardDelay                 1587
#define IDC_CenterRadioGlobalDot        1588
#define IDC_RewardTrainingMode          1589
#define IDC_xLocR                       1590
#define IDC_FixLocR                     1590
#define IDC_yLocR                       1591
#define IDC_DisplayDuringChoice         1591
#define IDC_UseShapes                   1592
#define IDC_SameBG                      1593
#define IDC_OccludeBG                   1594
#define IDC_RFX                         1595
#define IDC_DebugResponderOn            1595
#define IDC_RFY                         1596
#define IDC_DebugLabelsOn               1596
#define IDC_DevX                        1597
#define IDC_DevY                        1598
#define IDC_EDIT11                      1600
#define IDC_Speed                       1600
#define IDC_DotGratings                 1601
#define IDC_DotGratingContrast          1602
#define IDC_DotGratingCycles            1603
#define IDC_LeftEyeStaticR              1604
#define IDC_RightEyeStaticR             1605
#define IDC_LeftEyeStaticB              1606
#define IDC_RightEyeStaticB             1607
#define IDC_SeparationV                 1608
#define IDC_ShowDisparity               1609
#define IDC_SwapRedBlue                 1610
#define IDC_UseKeyboard                 1611
#define IDC_PurpleCount                 1612
#define IDC_FinalSize                   1613
#define IDC_InitialSize                 1614
#define IDC_TypeAutoRFMap               1615
#define IDC_RFMapL                      1616
#define IDC_RFL                         1617
#define IDC_RFR                         1618
#define IDC_TotalTrials                 1619
#define IDC_Pause2                      1620
#define IDC_Random                      1621
#define IDC_saccadeDisplayNoise         1624
#define IDC_saccadeSameBgTrial          1627
#define IDC_saccadeAlternateNoise       1628
#define IDC_saccadeNoisePercent         1629
#define IDC_saccadeNoiseRed             1630
#define IDC_saccadeNoiseGreen           1631
#define IDC_saccadeNoiseBlue            1632
#define IDC_saccadeNoiseSize            1633
#define IDC_saccadeOccludeBG            1634
#define IDC_saccadeNoiseStatic          1635
#define IDC_tbsPrimaryRed               1636
#define IDC_tbsPrimaryGreen             1637
#define IDC_tbsPrimaryBlue              1638
#define IDC_tbsSecondaryRed             1639
#define IDC_tbsSecondaryGreen           1640
#define IDC_tbsSecondaryBlue            1641
#define IDC_tbsPrimaryStatic            1642
#define IDC_tbsSecondaryStatic          1643
#define IDC_tbsDebugResponderOn         1644
#define IDC_tbsDebugLabelsOn            1645
#define IDC_tbsSaccadeHoldDelay         1646
#define IDC_tbsTargetActivePeriod       1646
#define IDC_tbsMisbehaviorDelay         1647
#define IDC_tbsRewardNormalMode         1648
#define IDC_tbsTertiaryRed              1648
#define IDC_tbsRewardAdvancedMode       1649
#define IDC_tbsTertiaryGreen            1649
#define IDC_tbsRewardBeginnerMode       1650
#define IDC_tbsTertiaryBlue             1650
#define IDC_tbsTrainingSaccadeHoldTime  1651
#define IDC_tbsSaccadeHoldTime          1651
#define IDC_tbsSaccadeHoldPeriod        1651
#define IDC_tbsRewardDelay              1652
#define IDC_tbsWrongDelay               1653
#define IDC_tbsPauseDotOff              1654
#define IDC_tbsPauseDotOn               1655
#define IDC_tbsTertiaryStatic           1656
#define IDC_tbsCenterDotSize            1657
#define IDC_tbsCrossPix                 1658
#define IDC_tbsCenterXPos               1659
#define IDC_tbsCenterXPosPrim           1659
#define IDC_tbsCenterYPos               1660
#define IDC_tbsCenterYPosPrim           1660
#define IDC_tbscStepSizeDeg             1661
#define IDC_tbsNumStepsX                1662
#define IDC_tbsNumStepsY                1663
#define IDC_tbsPeriphDotSize            1664
#define IDC_tbsStepSize                 1665
#define IDC_tbsNumStepsH                1666
#define IDC_tbsNumStepsV                1667
#define IDC_tbsSeparationV              1668
#define IDC_tbsAngleOffset              1668
#define IDC_tbsFlashInterval            1669
#define IDC_tbsRandomizeFlashInterval   1670
#define IDC_tbsFlashIntervalRandMin     1671
#define IDC_tbsFlashIntervalRandMax     1672
#define IDC_tbsShowCenterFlash          1673
#define IDC_tbsDisplayTime              1674
#define IDC_tbsRandomizeDisplayTime     1675
#define IDC_tbsDisplayRandMin           1676
#define IDC_tbsDisplayRandMax           1677
#define IDC_tbsPeriphRadioPrimary       1678
#define IDC_tbsPeriphRadioSecondary     1679
#define IDC_tbsPeriphRadioRandomize     1680
#define IDC_tbsNumRedTrials             1681
#define IDC_tbsPctRedTrials             1681
#define IDC_tbsFixationFlashDelay       1682
#define IDC_tbsPeriphRadioAlternate     1683
#define IDC_tbsDisplayDuringHoldPeriod  1684
#define IDC_tbsUseShapes                1685
#define IDC_tbsDotGratings              1686
#define IDC_tbsDotGratingContrast       1687
#define IDC_tbsDotGratingCycles         1688
#define IDC_tbsCenterRadioPrimary       1689
#define IDC_tbsCenterRadioSecondary     1690
#define IDC_tbsCenterRadioAlternate     1691
#define IDC_tbsAlternateBlockSize       1692
#define IDC_tbsCenterRadioRandomize     1693
#define IDC_tbsRadiusOffset             1694
#define IDC_tbsReadPointsFromFile       1695
#define IDC_tbsGridRadioCartesian       1695
#define IDC_tbsUseNoise                 1696
#define IDC_tbsSameBG                   1697
#define IDC_tbsInterleaveNoise          1698
#define IDC_tbsOccludeBG                1699
#define IDC_tbsNoiseSize                1700
#define IDC_tbsNoisePct                 1701
#define IDC_tbsNoiseRed                 1702
#define IDC_tbsNoiseGreen               1703
#define IDC_tbsNoiseBlue                1704
#define IDC_tbsNoiseStatic              1705
#define IDC_tbsUseApprox                1706
#define IDC_tbsAvoidZero                1707
#define IDC_tbsGridRadioRadial          1708
#define IDC_tbsAngle270                 1709
#define IDC_tbsAngle90                  1710
#define IDC_tbsAngle180                 1711
#define IDC_tbsAngle0                   1712
#define IDC_tbsButtonApply              1713
#define IDC_tbsShowCenterHold           1714
#define IDC_tbsSchemeDescription        1715
#define IDC_tbsAdvanceEitherEye         1715
#define IDC_tbsAngle45                  1716
#define IDC_tbsTrialResults_RR_R        1717
#define IDC_tbsTrialResults_RR_W        1718
#define IDC_tbsTrialResults_RR_T        1719
#define IDC_tbsTrialResults_RB_R        1720
#define IDC_tbsTrialResults_RB_W        1721
#define IDC_tbsTrialResults_RB_T        1722
#define IDC_tbsTrialResults_BR_R        1723
#define IDC_tbsTrialResults_BR_W        1724
#define IDC_tbsTrialResults_BR_T        1725
#define IDC_tbsTrialResults_BB_R        1726
#define IDC_tbsTrialResults_BB_W        1727
#define IDC_tbsTrialResults_BB_T        1728
#define IDC_tbsTrialResults_R_T         1729
#define IDC_tbsTrialResults_W_T         1730
#define IDC_tbsTrialResults_BB_T2       1731
#define IDC_tbsTrialResults_Total       1731
#define IDC_tbsAngle135                 1732
#define IDC_tbsAngle225                 1733
#define IDC_tbsAngle315                 1734
#define IDC_tbsRadius0                  1735
#define IDC_tbsRadius5                  1736
#define IDC_tbsRadius10                 1737
#define IDC_tbsRadiusOrigin             1738
#define IDC_tbsPctBlueTrials            1739
#define IDC_tbsEyeCoverageRadioRandom   1740
#define IDC_grEyePosnDisplayLX          1740
#define IDC_tbsEyeCoverageRadioSpatiotopic 1740
#define IDC_tbsEyeCoverageRadioReciprocal 1741
#define IDC_grEyePosnDisplayLY          1741
#define IDC_tbsEyeCoverageRadioRetinotopic 1741
#define IDC_tbsEyeCoverageDescription   1742
#define IDC_grEyePosnDisplayRX          1742
#define IDC_tbsDeviationAngle           1743
#define IDC_grEyePosnDisplayRY          1743
#define IDC_tbsRadius20                 1744
#define IDC_rfmCrossY                   1744
#define IDC_tbsRadius25                 1745
#define IDC_STATICfield                 1745
#define IDC_tbsRadius30                 1746
#define IDC_STATICfield2                1746
#define IDC_statusBorder                1746
#define IDC_tbsRadius15                 1747
#define IDC_rfmCrossDiameter            1747
#define IDC_smStatusDisplay             1747
#define IDC_tbsGridSettingsRadioRandom  1748
#define IDC_rfmCrossThickness           1748
#define IDC_tbsGridSettingsRadioCyclopean 1749
#define IDC_rfmCrossY2                  1749
#define IDC_tbsGridSettingsDescription  1750
#define IDC_STATICfield3                1750
#define IDC_tbsInfoDisplay              1751
#define IDC_tbsBlankTimeOutScreen       1752
#define IDC_tbsEyePosnDisplayLX         1753
#define IDC_grLeftEyeAutoRF             1753
#define IDC_grRightEyeAuto              1754
#define IDC_grRightEyeAutoRF            1754
#define IDC_tbsTrialResults_RP_R        1754
#define IDC_tbsPeriphRadioTertiary      1755
#define IDC_tbsEyePosnDisplayLY         1756
#define IDC_tbsPctRedCtr                1757
#define IDC_tbsCenterRadioTertiary      1758
#define IDC_tbsEyePosnDisplayRX         1759
#define IDC_tbsEyePosnDisplayLY2        1760
#define IDC_tbsEyePosnDisplayRY         1760
#define IDC_tbsPctBlueCtr               1761
#define IDC_tbsTrialResults_RP_W        1762
#define IDC_tbsTrialResults_RP_T        1763
#define IDC_tbsPctPplTrials             1764
#define IDC_tbsTrialResults_BP_R        1764
#define IDC_tbsAlternateWithPurple      1765
#define IDC_tbsSaccadeTriggerRadioSubject 1766
#define IDC_tbsSaccadeTriggerRadioCue   1767
#define IDC_tbsTrialResults_BP_W        1768
#define IDC_tbsTrialResults_BP_T        1769
#define IDC_tbsTrialResults_PR_R        1770
#define IDC_tbsTrialResults_PR_W        1771
#define IDC_tbsTrialResults_PR_T        1772
#define IDC_tbsTrialResults_PB_R        1773
#define IDC_tbsTrialResults_PB_W        1774
#define IDC_tbsTrialResults_PB_T        1775
#define IDC_tbsTrialResultsBorderPrimary 1776
#define IDC_tbsTrialResultsBorderSecondary 1777
#define IDC_tbsTrialResultsBorderTertiary 1778
#define IDC_tbsTrialResults_PP_R        1779
#define IDC_tbsTrialResults_PP_W        1780
#define IDC_tbsTrialResults_PP_T        1781
#define IDC_tbsTrialSequenceImgCross    1782
#define IDC_tbsTrialSequenceImgTimeScale2 1783
#define IDC_tbsTrialSequenceImgTimeScale 1783
#define IDC_fsUseNoise                  1784
#define IDC_tbsCenterXPosSec            1784
#define IDC_fsSameBG                    1785
#define IDC_tbsCenterYPos2              1785
#define IDC_tbsCenterYPosSec            1785
#define IDC_fsInterleaveNoise           1786
#define IDC_tbsDisplayDuringHoldPeriod2 1786
#define IDC_tbsCueTrainingMode          1786
#define IDC_tbsTrialSequenceImgDot      1787
#define IDC_fsOccludeBG                 1787
#define IDC_fsNoiseSize                 1788
#define IDC_tbsStimRightEye             1788
#define IDC_fsNoisePct                  1789
#define IDC_fsNoiseCoverage             1789
#define IDC_tbsAngleFlux                1789
#define IDC_fsNoiseColorDisplay         1790
#define IDC_fsNoiseCommon               1790
#define IDC_tbsRadialFlux               1790
#define IDC_tbsRadiusFlux               1790
#define IDC_fsNoiseColorRed             1791
#define IDC_tbsStimLeftEye              1791
#define IDC_fsNoiseColorGreen           1792
#define IDC_fsNoiseColorBlue            1793
#define IDC_fsCrosshairDiameter         1794
#define IDC_fsCrosshairThickness        1795
#define IDC_fsFixationTime              1796
#define IDC_fsLeftFixationNoOccAtCtr    1800
#define IDC_fsLeftFixationNoOccAtHalf   1801
#define IDC_fsLeftFixationNoOccAtPeriph 1802
#define IDC_fsLeftColorRed              1803
#define IDC_fsLeftColorGreen            1804
#define IDC_fsLeftColorBlue             1805
#define IDC_fsRightColorRed             1806
#define IDC_fsRightColorGreen           1807
#define IDC_fsRightColorBlue            1808
#define IDC_fsRightColorDisplay         1809
#define IDC_fsLeftColorDisplay          1810
#define IDC_fsLeftEyeFixatingDeviation  1811
#define IDC_fsRightEyeFixatingDeviation 1812
#define IDC_fsLeftFixationOccAtCtr      1813
#define IDC_fsLeftFixationOccAtHalf     1814
#define IDC_fsLeftFixationOccAtPeriph   1815
#define IDC_fsRightFixationNoOccAtCtr   1816
#define IDC_fsRightFixationNoOccAtHalf  1817
#define IDC_fsRightFixationNoOccAtPeriph 1818
#define IDC_fsRightFixationOccAtCtr     1819
#define IDC_fsRightFixationOccAtHalf    1820
#define IDC_fsRightFixationOccAtPeriph  1821
#define IDC_fsApply                     1822
#define IDC_fsLeftColorStatic           1823
#define IDC_fsRightColorStatic          1824
#define IDC_fsNoiseColorStatic          1825
#define IDC_useGlobalColors             1827
#define IDC_tbsAdvanceOnBrokenCue       1828
#define IDC_CalibrationCheckPursuit     1829
#define IDC_CalibrationDefaultSeparation 1830
#define IDC_rfmStimColorStatic          1831
#define IDC_rfmStimRed                  1832
#define IDC_rfmStimGreen                1833
#define IDC_rfmStimBlue                 1834
#define IDC_tbsDifficultySlider         1835
#define IDC_tbsDifficultyDescription    1836
#define IDC_rfmBinocular                1837
#define IDC_rfmPrimaryRed               1839
#define IDC_rfmPrimaryGreen             1840
#define IDC_rfmPrimaryBlue              1841
#define IDC_rfmSecondaryRed             1842
#define IDC_rfmSecondaryGreen           1843
#define IDC_rfmSecondaryBlue            1844
#define IDC_revSecondaryBlue            1844
#define IDC_rfmTertiaryRed              1845
#define IDC_rfmTertiaryGreen            1846
#define IDC_rfmTertiaryBlue             1847
#define IDC_rfmUseNoise                 1848
#define IDC_rfmSameBG                   1849
#define IDC_rfmInterleaveNoise          1850
#define IDC_rfmOccludeBG                1851
#define IDC_rfmNoiseSize                1852
#define IDC_rfmNoisePct                 1853
#define IDC_rfmNoiseRed                 1854
#define IDC_rfmNoiseGreen               1855
#define IDC_rfmNoiseBlue                1856
#define IDC_rfmPrimaryStatic            1857
#define IDC_rfmSecondaryStatic          1858
#define IDC_revSecondaryStatic          1858
#define IDC_rfmTertiaryStatic           1859
#define IDC_rfmNoiseStatic              1860
#define IDC_ReverseShutters             1861
#define IDC_rfmCheckPrimaryL            1862
#define IDC_rfmDebug                    1863
#define IDC_rfmEyePosnDisplayLX         1864
#define IDC_rfmEyePosnDisplayLY         1865
#define IDC_rfmEyePosnDisplayRX         1866
#define IDC_rfmEyePosnDisplayRY         1867
#define IDC_rfmWaitTarget               1868
#define IDC_rfmWait                     1868
#define IDC_tbsShowLeftEye              1869
#define IDC_tbsShowRightEye             1870
#define IDC_tbsSaveGrid                 1871
#define IDC_revModeInitLoop             1873
#define IDC_revModeFoveaLoop            1874
#define IDC_revModeTest                 1875
#define IDC_revPrimaryRed               1876
#define IDC_revPrimaryGreen             1877
#define IDC_revPrimaryBlue              1878
#define IDC_revPrimaryStatic            1879
#define IDC_revSecondaryRed             1880
#define IDC_revSecondaryGreen           1881
#define IDC_revInitLeft                 1882
#define IDC_revInitRight                1883
#define IDC_revDotSize                  1884
#define IDC_revDisplayTime              1885
#define IDC_revEyePosnDisplayLX         1886
#define IDC_revEyePosnDisplayLY         1887
#define IDC_revEyePosnDisplayRX         1888
#define IDC_revEyePosnDisplayRY         1889
#define IDC_revWait                     1890
#define IDC_revDebug                    1891
#define IDC_snLoadStimFolder            1893
#define IDC_snCreateStimFolder          1894
#define IDC_snStimWidth                 1895
#define IDC_snLightCount                1896
#define IDC_snPrimaryCount              1896
#define IDC_snCrossX                    1897
#define IDC_snCrossY                    1898
#define IDC_snCrossDiameter             1899
#define IDC_snCrossThickness            1900
#define IDC_snBinocular                 1901
#define IDC_snCrossX2                   1902
#define IDC_snCrossY2                   1903
#define IDC_snSwapInt                   1904
#define IDC_snEyePosnDisplayLX          1905
#define IDC_snEyePosnDisplayLY          1906
#define IDC_snEyePosnDisplayRX          1907
#define IDC_snEyePosnDisplayRY          1908
#define IDC_snWait                      1909
#define IDC_snWindowAllowancePix        1910
#define IDC_snDisplayTimeMs             1911
#define IDC_snDebug                     1912
#define IDC_snPrimaryRed                1913
#define IDC_snPrimaryGreen              1914
#define IDC_snPrimaryBlue               1915
#define IDC_sparsePrimaryStatic         1916
#define IDC_snSecondaryRed              1917
#define IDC_snSecondaryGreen            1918
#define IDC_snSecondaryBlue             1919
#define IDC_sparseSecondaryStatic       1920
#define IDC_snBGRed                     1921
#define IDC_snBGGreen                   1922
#define IDC_snBGBlue                    1923
#define IDC_sparseBGStatic              1924
#define IDC_snTertiaryRed               1925
#define IDC_snTertiaryGreen             1926
#define IDC_snTertiaryBlue              1927
#define IDC_snSeed                      1928
#define IDC_STATICSEED                  1929
#define IDC_sparseTertiaryStatic        1930
#define IDC_snShutters                  1932
#define IDC_EditAmp                     1933
#define IDC_snUseGrid                   1935
#define IDC_snStepSizeDeg               1936
#define IDC_snNumStepsX                 1937
#define IDC_snStepsY                    1938
#define IDC_snNumStepsY                 1938
#define IDC_STATICEyePositions          65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1939
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
